import { Suspense } from 'react';
import Loading from './loading';
import StyledComponentsRegistry from '../lib/registry';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Suspense fallback={<Loading/>}>
          {children}
          </Suspense>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
