import { Suspense } from 'react';
import { Inter } from 'next/font/google'
import Loading from './loading';
import StyledComponentsRegistry from '../lib/registry';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={`${inter.className}`}>
          <StyledComponentsRegistry>
            <Suspense fallback={<Loading/>}>
            {children}
            </Suspense>
          </StyledComponentsRegistry>
        </main>
      </body>
    </html>
  )
}
